Write a Python program to convert an array to an ordinary list with the same items.

In [ ]:
from array import *
array_num = array('i', [1, 3, 5, 3, 7, 1, 9, 3])
print("Original array: "+str(array_num))
num_list = array_num.tolist()
print("Convert the said array to an ordinary list with the same items:")
print(num_list)

Original array: array('i', [1, 3, 5, 3, 7, 1, 9, 3])
Convert the said array to an ordinary list with the same items:
[1, 3, 5, 3, 7, 1, 9, 3]


Write a NumPy program to compute the sum of the diagonal elements of a given array.

In [ ]:
import numpy as np
m = np.arange(6).reshape(2,3)
print("Original matrix:")
print(m)
result =  np.trace(m)
print("Condition number of the said matrix:")
print(result)

Original matrix:
[[0 1 2]
 [3 4 5]]
Condition number of the said matrix:
4


Write a NumPy program to subtract the mean of each row of a given matrix.

In [ ]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.47026506 0.5175881  0.91790924 0.82218905 0.5117456  0.79123537
  0.43302033 0.15903802 0.21864217 0.55140483]
 [0.97050921 0.54766958 0.92462562 0.8129171  0.86165006 0.19579883
  0.15194355 0.12531476 0.975024   0.33261427]
 [0.35957625 0.16338472 0.90931827 0.71197017 0.04550847 0.60433558
  0.71179907 0.27811954 0.88287391 0.63777061]
 [0.56467182 0.71225761 0.96776552 0.18717132 0.09251254 0.52221712
  0.47896321 0.48964085 0.97042903 0.03346408]
 [0.00137722 0.42548344 0.57183751 0.26260949 0.09995334 0.85192293
  0.86010583 0.66688264 0.03442851 0.59360719]]

Subtract the mean of each row of the said matrix:

[[-0.06903872 -0.02171568  0.37860547  0.28288527 -0.02755818  0.2519316
  -0.10628345 -0.38026576 -0.3206616   0.01210105]
 [ 0.38070251 -0.04213712  0.33481892  0.2231104   0.27184336 -0.39400787
  -0.43786315 -0.46449194  0.38521731 -0.25719243]
 [-0.17088941 -0.36708094  0.37885261  0.18150451 -0.48495719  0.07386992
   0.18133341 -0.25234612  0.35

Given two arrays A&B having the same shape. 


In [7]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
c = a+b
print(c)


[[ 8 10 12]
 [14 16 18]]


Write a NumPy program to subtract the mean of each row of a given matrix.

In [8]:
import numpy as np
print("matrix")
X = np.random.rand(5, 10)
print(X)
print("matrix")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

matrix
[[0.91773139 0.29806206 0.78746397 0.83774753 0.72064987 0.50484942
  0.06034189 0.03818723 0.45598633 0.34972764]
 [0.56165033 0.12032983 0.46783504 0.9792407  0.17254791 0.78595062
  0.20390358 0.61003705 0.40111913 0.77369417]
 [0.9449648  0.3229412  0.7590468  0.03051926 0.62724723 0.31403027
  0.66863009 0.0767624  0.92048759 0.9040237 ]
 [0.3788644  0.95083137 0.0194533  0.05459209 0.41455736 0.27755042
  0.84740627 0.01214256 0.47611444 0.82526672]
 [0.26596178 0.28407509 0.19088345 0.10980323 0.70335457 0.3782266
  0.67478495 0.00108386 0.19073577 0.38775513]]
matrix
[[ 0.42065666 -0.19901267  0.29038923  0.3406728   0.22357513  0.00777469
  -0.43673285 -0.4588875  -0.04108841 -0.14734709]
 [ 0.05401949 -0.387301   -0.0397958   0.47160986 -0.33508292  0.27831978
  -0.30372725  0.10240621 -0.10651171  0.26606333]
 [ 0.38809947 -0.23392414  0.20218146 -0.52634608  0.0703819  -0.24283506
   0.11176476 -0.48010294  0.36362226  0.34715836]
 [-0.0468135   0.52515348 -0.4062245